moedas = {"AED":" Dirham dos Emirados Árabes Unidos",
"AFN":" Afegane Afegão",
"ALL":" Lek Albanês",
"AMD":" Dram Armênio",
"ANG":" Florim das Antilhas Holandesas",
"AOA":" Kwanza Angolano",
"ARS":" Peso Argentino",
"AUD":" Dólar Australiano",
"AWG":" Florim Arubano",
"AZN":" Manat Azerbaijano",
"BAM":" Marco Conversível da Bósnia e Herzegovina",
"BBD":" Dólar de Barbados",
"BDT":" Taka Bengali",
"BGN":" Lev Búlgaro",
"BHD":" Dinar Bareinita",
"BIF":" Franco Burundiano",
"BMD":" Dólar Bermudense",
"BND":" Dólar de Brunei",
"BOB":" Boliviano",
"BRL":" Real Brasileiro",
"BSD":" Dólar Bahamense",
"BTN":" Ngultrum Butanês",
"BWP":" Pula de Botswana",
"BYR":" Rublo Bielorrusso",
"BZD":" Dólar Belizeano",
"CAD":" Dólar Canadense",
"CDF":" Franco Congolês",
"CHF":" Franco Suíço",
"CLP":" Peso Chileno",
"CNY":" Yuan Renminbi Chinês",
"COP":" Peso Colombiano",
"CRC":" Colón Costarriquenho",
"CUC":" Peso Cubano Conversível",
"CUP":" Peso Cubano",
"CVE":" Escudo Caboverdiano",
"CZK":" Coroa Tcheca",
"DJF":" Franco do Djibuti",
"DKK":" Coroa Dinamarquesa",
"DOP":" Peso Dominicano",
"DZD":" Dinar Argelino",
"EGP":" Libra Egípcia",
"ERN":" Nakfa Eritreia",
"ETB":" Birr Etíope",
"EUR":" Euro",
"FJD":" Dólar de Fiji",
"FKP":" Libra das Ilhas Falkland",
"GBP":" Libra Esterlina",
"GEL":" Lari Georgiano",
"GGP":" Libra de Guernsey",
"GHS":" Cedi Ganês",
"GIP":" Libra de Gibraltar",
"GMD":" Dalasi Gambiano",
"GNF":" Franco Guineense",
"GTQ":" Quetzal Guatemalteco",
"GYD":" Dólar da Guiana",
"HKD":" Dólar de Hong Kong",
"HNL":" Lempira Hondurenha",
"HRK":" Kuna Croata",
"HTG":" Gourde Haitiano",
"HUF":" Forint Húngaro",
"IDR":" Rupia Indonésia",
"ILS":" Novo Shekel Israelense",
"IMP":" Libra de Man",
"INR":" Rupia Indiana",
"IQD":" Dinar Iraquiano",
"IRR":" Rial Iraniano",
"ISK":" Coroa Islandesa",
"JEP":" Libra de Jersey",
"JMD":" Dólar Jamaicano",
"JOD":" Dinar Jordaniano",
"JPY":" Iene Japonês",
"KES":" Xelim Queniano",
"KGS":" Som Quirguiz",
"KHR":" Riel Cambojano",
"KMF":" Franco Comorense",
"KPW":" Won NorteCoreano",
"KRW":" Won SulCoreano",
"KWD":" Dinar Kuwaitiano",
"KYD":" Dólar das Ilhas Cayman",
"KZT":" Tenge Cazaque",
"LAK":" Kip de Laos",
"LBP":" Libra Libanesa",
"LKR":" Rupia do Sri Lanka",
"LRD":" Dólar Liberiano",
"LSL":" Loti do Lesoto",
"LTL":" Litas lituana",
"LVL":" Lat Letonia",
"LYD":" Dinar líbio",
"MAD":" Dirham marroquino",
"MDL":" Leu moldavo",
"MGA":" Ariary malgaxe",
"MKD":" Dinar macedônio",
"MMK":" Kyat de Mianmar",
"MNT":" Tugrik mongol",
"MOP":" Pataca de Macau",
"MRO":" Ouguiya mauritana",
"MUR":" Rupia Mauriciana",
"MVR":" Rufiyaa das Maldivas",
"MWK":" Kwacha do Malawi",
"MXN":" Peso Mexicano",
"USD":" Dólar Americano",
'ADA':'Cardano',
'ALGO':'Algorand',
'AMP':'Amp',
'ATOM':'Cosmos',
'AVAX':'Avalanche',
'AXS':'Axie Infinity',        
'BAKE':'BakeryToken',
'BAT':'Basic Attention Token',
'BCH':'Bitcoin Cash',
'BTC':'Bitcoin',
'BTCB':'Bitcoin BEP2',        
'BTG':'Bitcoin Gold',
'BUSD':'Binance USD',
'BNB':'Bnb',
'BSV':'Bitcoin SV',
'BSW':'Biswap',
'CELO':'Celo',
'CHZ':'Chiliz',
'COMP':'Compound',
'CRO':'Cronos',
'CRV':'Curve DAO Token',      
'CAKE':'PancakeSwap',
'DAI':'Dai',
'DASH':'Dash',
'DCR':'Decred',
'DFI':'Defichain',
'DOGE':'Dogecoin',
'DOT':'Polkadot',
'EGLD':'MultiversX',
'ENJ':'Enjin Coin',
'EOS':'EOS',
'ETC':'Ethereum Classic',     
'ETH':'Ethereum',
'FEI':'Fei USD',
'FIL':'Filecoin',
'FLOW':'Flow',
'FRAX':'Frax',
'FTM':'Fantom',
'FTT':'FTX Token',
'GRT':'The Graph',
'GNO':'Gnosis',
'HBAR':'Hedera',
'HOT':'Holo',
'HNT':'Helium',
'ICP':'Internet Computer',    
'INJ':'Injective',
'KAVA':'Kava',
'KCS':'KuCoin Token',
'KDA':'Kadena',
'KLAY':'Klaytn',
'KNC':'Kyber Network Crystal',
'KSM':'Kusama',
'LEO':'UNUS SED LEO',
'LINK':'Chainlink',
'LRC':'Loopring',
'LTC':'Litecoin',
'LUNA':'Terra',
'MIOTA':'IOTA',
'MKR':'Maker',
'MATIC':'Polygon',
'MANA':'Decentraland',
'MINA':'Mina',
'NANO':'Nanomatic',
'NEAR':'NEAR Protocol',
'NEO':'Neo',
'NEXO':'Nexo',
'OKB':'OKB',
'OMG':'OMG Network',
'ONE':'Harmony',
'PAXG':'PAX Gold',
'QTUM':'Qtum',
'RUNE':'THORChain',
'SAND':'The Sandbox',
'SHIB':'Shiba Inu',
'SOL':'Solana',
'SRM':'Serum',
'STX':'Stacks',
'THETA':'Theta Network',
'TRX':'TRON',
'TUSD':'TrueUSD',
'UNI':'Uniswap',
'USDC':'USD Coin',
'USDP':'USDP Stablecoin',
'USDT':'Tether',
'VET':'VeChain',
'WBTC':'Wrapped Bitcoin',
'XLM':'Stellar',
'XMR':'Monero',
'XRP':'XRP',
'XTZ':'Tezos',
'ZEC':'Zcash'}